version: 0.{build}

branches:
  only:
    - main

image:
- Visual Studio 2019
- Ubuntu

skip_branch_with_pr: true
stack: python 3.13

install:
- pip install -r requirements.txt
- pip install PyInstaller

build_script:
- ps: Set-Content -Path src/version.py -Value "ver=`"$env:APPVEYOR_BUILD_VERSION`"" -Encoding ascii
- flet pack src/main.py --name Fuji --icon src/assets/rlogo.ico --onedir --add-data=src/locales:locales --add-data=src/assets:assets --yes

test: off

#
#   Windows package
# 
for:
-
  matrix:
    only:
    - image: Visual Studio 2019

  after_build:
  - 7z a Fuji-Windows-amd64.zip %CD%\dist\Fuji

  artifacts:
  - path: Fuji-Windows-amd64.zip

#
#   Linux package
# 
-
  matrix:
    only:
    - image: Ubuntu

  build_script:
  - echo "ver=\"$APPVEYOR_BUILD_VERSION\"" > src/version.py
  - flet pack src/main.py --name Fuji --icon src/assets/rlogo.ico --onedir --add-data=src/locales:locales --add-data=src/assets:assets --yes

  after_build:
  - tar -czvf Fuji-Linux-amd64.tar.gz -C dist Fuji

  artifacts:
  - path: Fuji-Linux-amd64.tar.gz
